### ISSUE TITLE
Deployed the app access the Denied

### ISSUE THREAD

**Issue by Soumik-Kumar-Baithalu-PI** [pnp/action-cli-deploy#40]
![Image](https://github.com/user-attachments/assets/3b987789-dcde-4f12-a18a-d6324e60b268)

![Image](https://github.com/user-attachments/assets/a79a4937-bbb2-4ae2-8e76-9683717135eb)

this deployed code 
```
`      - name: CLI for Microsoft 365 Login
        uses: pnp/action-cli-login@v2.2.4
        with:
          CERTIFICATE_ENCODED: ${{ secrets.CERTIFICATE_ENCODED }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          APP_ID: ${{ secrets.APP_ID }}
          TENANT: ${{ secrets.TENANT_ID }}
        env:
          M365_CLIENT_ID: ${{ secrets.APP_ID }}
          M365_CLIENT_SECRET: ${{ secrets.CERTIFICATE_PASSWORD }}
          M365_TENANT_ID: ${{ secrets.TENANT_ID }}

      - name: CLI for Microsoft 365 Deploy App
        id : M365clideploy  
        uses: pnp/action-cli-deploy@v4.0.0
        with:
          APP_FILE_PATH: /home/runner/work/Software-Installation-Checklist-/Software-Installation-Checklist-/sharepoint/solution/software-installation-checklist.sppkg
          SKIP_FEATURE_DEPLOYMENT: true
          OVERWRITE: true

      - name: Get the id of the app deployed
        run: echo "The id of the app deployed is ${{ steps.M365clideploy.outputs.APP_ID }}"`
```
