### ISSUE TITLE
Action doesn't seem to do anything

### ISSUE THREAD

**Issue by JamesDerrickHH** [pnp/action-cli-deploy#42]
It definitely feels like a me problem, so any help would be greatly appreciated
I have a build and deploy script, and am basically just trying to get the default helloworld webpart that yeoman creates for you uploaded to my sharepoint (at the tenant level)

The script seems quite basic and the github action completes without error, but the app package doesn't seem to go anywhere and I don't get any id return to me
```
name: Build and Deploy the SPFx WebPart with Microsoft 365 CLI

on:   
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Gulp globally
      run: npm i -g gulp
    
    - name: Bundle and package
      run: |
        gulp bundle --ship
        gulp package-solution --ship

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Log in to tenant
      uses: pnp/action-cli-login@v3
      with:
        TENANT: ${{ secrets.TENANT_ID }}
        APP_ID: ${{ secrets.APP_ID }}
        CERTIFICATE_ENCODED: ${{ secrets.CERTIFICATE_ENCODED }}
        CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
    
    - name: Deploy app to tenant
      id: deploy
      uses: pnp/action-cli-deploy@v5.0.0
      with:
        APP_FILE_PATH: sharepoint/solution/sharepoint-deploy-demo.sppkg
        SKIP_FEATURE_DEPLOYMENT: true
        OVERWRITE: true
    
    # Print the id of the app
    - name: Get the id of the app deployed
      run: echo "The id of the app deployed is ${{ steps.deploy.outputs.APP_ID }}"
```

![Image](https://github.com/user-attachments/assets/1fedfbcc-1098-4a0f-ba00-76e505cdb513)

The cli login action seems to work fine, and says login was successful, and my app registration has application level permission to Sites.FullControl.All
Not really sure what to try differently

**Comment by martinlingstuyl** [comment]
Hi @JamesDerrickHH, What I'm missing in your yaml is that you have two stages, but you don't publish the sppkg as an artifact in the first stage and download it in the deploy stage. you should do that, because the two stages are actually two separate machines running in the cloud somewhere. They don't have access to the same file system...

You could check the example pipeline in this blog:
https://www.voitanos.io/blog/sharepoint-framework-cicd-github-federated-identity/

(And you can update your flow to use Federated Identity, which is much easier than Certificates as well😉)

**Comment by JamesDerrickHH** [comment]
Looks like a classic case of me trying to run before I could walk. 
If I'd done it all in a single job in the first place it probs would have worked.
Thanks so much for the help, I've added upload and download artifact steps, still not working for me, but at least gives me more to investigate

![Image](https://github.com/user-attachments/assets/bffe0727-801c-4bb0-87c6-0c9e6af531d5)

**Comment by martinlingstuyl** [comment]
Awesome! You should get it working like this. I'll close the issue. If you have any questions feel free to reopen it...

**Comment by JamesDerrickHH** [comment]
Sorry, still no luck, and I'm not sure why, it is creating the artifact correctly, as I can download that manually and upload it to sharepoint myself, but just doesn't want to work with the deploy action
Current yaml looks like this...
```
name: Build and Deploy the SPFx WebPart with Microsoft 365 CLI

on:   
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Gulp globally
      run: npm i -g gulp
    
    - name: Bundle and package
      run: |
        gulp bundle --ship
        gulp package-solution --ship
    
    - name: Upload SharePoint package (*.sppkg)
      uses: actions/upload-artifact@v4
      with:
        name: SHAREPOINT_PACKAGE
        path: sharepoint/solution/sharepoint-deploy-demo.sppkg
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download SharePoint package (*.sppkg)
      uses: actions/download-artifact@v4
      with:
        name: SHAREPOINT_PACKAGE
        path: artifact

    - name: Display downloaded SharePoint package
      run: ls -la artifact

    - name: Log in to tenant
      uses: pnp/action-cli-login@v3
      with:
        TENANT: ${{ secrets.TENANT_ID }}
        APP_ID: ${{ secrets.APP_ID }}
        CERTIFICATE_ENCODED: ${{ secrets.CERTIFICATE_ENCODED }}
        CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
    
    - name: Deploy app to tenant
      id: deploy
      uses: pnp/action-cli-deploy@v5.0.0
      with:
        APP_FILE_PATH: artifact/sharepoint-deploy-demo.sppkg
        SKIP_FEATURE_DEPLOYMENT: true
        OVERWRITE: true
    
    # Print the id of the app
    - name: Get the id of the app deployed
      run: echo "The id of the app deployed is ${{ steps.deploy.outputs.APP_ID }}"
```

And output in github looks like this...

![Image](https://github.com/user-attachments/assets/027ff405-ef7d-4be4-a82b-5f675c647690)

If I don't use the path attribute in the download artifact action and use `SHAREPOINT_PACKAGE/sharepoint-deploy-demo.sppkg` then it fails silently like it did before
definitely feels like I'm missing something simple, just can't see it
